### ISSUE TITLE
As a fan of giraffes, I would like to have the list of Giraffe Facts added to the website so that I can see stuff about giraffes.

### ISSUE THREAD

**Issue by randyhart** [randyhart/tech-time#10]
Add the list of giraffe facts that was compiled by @tbaxter-18f and @mgwalker https://github.com/18F/18f-bot-facts/blob/master/giraffes.json

**Comment by randyhart** [comment]
done

**Comment by mgwalker** [comment]
Hi @randyhart. Where is your requirements traceability matrix?  How do we know this is done?
