### ISSUE TITLE
Site Availability Problems

### ISSUE THREAD

**Issue by randyhart** [randyhart/tech-time#5]
User Story:
As the owner of https://techrandy.app.cloud.gov/, I would like the site to be available all the time, so that I can share my #content with everyone on the internet.

**Comment by wslack** [comment]
As a consumer of https://techrandy.app.cloud.gov/, I would like the site to be available all the time, so that I can consume Randy's #content worldwide.

**Comment by randyhart** [comment]
@wslack thanks for your feedback. I understand from my team that they are aware of the issue and will work on it after tonight's Washington Capitals game. If they are too tired after the Capitals game, they will try to address the issue tomorrow. The team understands how great it is for people to see the picture they took of the mountain in Alaska.

**Comment by randyhart** [comment]
our team has tried for the last hour to figure it out. they couldn't. this website is going to be dead forever. Sorry everyone.

**Comment by randyhart** [comment]
Pleased to report that the site is back online. The team woke up and remembered that everything about using cloud.gov sandbox is well-documented and easy to understand. We're adding a link to https://cloud.gov/docs/getting-started/your-first-deploy/ in case this comes up again. Thanks for your patience.

**Comment by randyhart** [comment]
Resolved!
